### ISSUE TITLE
一键部署出错

### ISSUE THREAD

**Issue by 9201314** [zkeq/Busuanzi_backend_self#2]
一键部署提示 Something went wrong

**Comment by zkeq** [comment]
可以提供详细的错误日志么？
我看下

**Comment by 9201314** [comment]
就是一键部署点进去就是显示 wrong
![image](https://user-images.githubusercontent.com/45234281/166394108-ec0db722-4245-4f1a-b3b3-2e4fa85c7d46.png)

**Comment by zkeq** [comment]
> 就是一键部署点进去就是显示 wrong ![image](https://user-images.githubusercontent.com/45234281/166394108-ec0db722-4245-4f1a-b3b3-2e4fa85c7d46.png)

似乎不能复现
![111](https://user-images.githubusercontent.com/62864752/166394204-3df2cdcd-c39d-47dd-824c-417110a593d1.png)

**Comment by zkeq** [comment]
> 就是一键部署点进去就是显示 wrong ![image](https://user-images.githubusercontent.com/45234281/166394108-ec0db722-4245-4f1a-b3b3-2e4fa85c7d46.png)

我这里好像可以跑
![222](https://user-images.githubusercontent.com/62864752/166394293-c3faceec-1364-418e-94a4-20cd0c8d383a.png)


你地址栏那个链接复制过来看下

**Comment by 9201314** [comment]
那知道了，应该是因为我没有登录 replit，感谢！第一次遇到 Issue 秒回的😂

**Comment by zkeq** [comment]
> 那知道了，应该是因为我没有登录 replit，感谢！第一次遇到 Issue 秒回的😂

嗯嗯嗯好，发邮件就看到了嘻嘻 🚀
