### ISSUE TITLE
一键部署报错

### ISSUE THREAD

**Issue by Cicada000** [zkeq/Busuanzi_backend_self#5]
您好，我在点击“RUN”按钮后看到这样的报错，请问该如何解决？

![image](https://user-images.githubusercontent.com/78632923/179163688-1cc50b01-38e0-40ff-84d1-0ead1f6f6124.png)

**Comment by zkeq** [comment]
我也试了下，发现 `replit` 

似乎并没有将本项目识别为 `python` 环境

之前是可以正常运行的...我找下解决方法

**Comment by zkeq** [comment]
似乎是 replit 的内部问题

目前提供以下解决方法

1. `replit` 创建一个 `Python` 模板新项目 

2. 复制本项目的文件到上一步创建的项目中

3. 点击 `🏃 RUN` 按钮，查看是否可以正常安装相关的依赖包

4. 若出现下图样式，即可说明安装成功。

![Snipaste_2022-07-15_18-49-58](https://user-images.githubusercontent.com/62864752/179209263-6c48b650-aa13-4477-b22c-a30f3ab54048.png)

**Comment by zkeq** [comment]
@Cicada000 请尝试提供的解决步骤，看下问题是否可以暂时得到解决。

**Comment by Cicada000** [comment]
按照着解决方法试了一遍，还是不行。replit识别出为python项目，但是在执行的时候还是报了一样的错😢

**Comment by zkeq** [comment]
直接 fork this https://replit.com/@zkeq/busuanzi

**Comment by zkeq** [comment]
![Snipaste_2022-07-17_10-03-25](https://user-images.githubusercontent.com/62864752/179380926-7e4ad8c7-42af-47ae-a8c9-6e3ebbf2c8f2.png)

**Comment by Cicada000** [comment]
直接Fork您的Replit仓库成功了，谢谢🤸‍♂️
